spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gs_data?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    druid:
      filters: stat,wall,log4j2
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 2
      filter:
        log4j2:
          statement-executable-sql-log-enable: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath*:com/gs/dao/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  config-location:
gs:
  #数据上传地址
  datauploadurl: http://52.83.241.9:8765/data/itemUpload
opc:
  server:
    url: 192.168.9.12
    id: E25E3A99-EB1A-40A9-9C49-42BFB0E439F0
    username: Administrator
    password: HollySys2008
logging:
  file: ../digitail-twin-data/logs/digitail-twin-data.log
  level:
    com.gs.*: info